# Generated by Django 5.2.17 on 2026-08-27 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='SessionEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_reserved', models.IntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reservations', to='inventory.equipment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='sessions_app.session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sessions_app.session')),
            ],
        ),
    ]
