# Generated by Django 5.2.17 on 2026-08-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_section_type'),
        ('inventory', '0001_initial'),
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date'], 'verbose_name': 'seance', 'verbose_name_plural': 'seances'},
        ),
        migrations.AlterModelOptions(
            name='sessionequipment',
            options={'verbose_name': 'reservation de materiel', 'verbose_name_plural': 'reservations de materiel'},
        ),
        migrations.AlterModelOptions(
            name='sessionsection',
            options={'verbose_name': 'section abordee', 'verbose_name_plural': 'sections abordees'},
        ),
        migrations.AddField(
            model_name='session',
            name='equipments',
            field=models.ManyToManyField(related_name='sessions', through='sessions_app.SessionEquipment', to='inventory.equipment'),
        ),
        migrations.AddField(
            model_name='session',
            name='sections',
            field=models.ManyToManyField(related_name='sessions', through='sessions_app.SessionSection', to='courses.section'),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sessionequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.equipment'),
        ),
        migrations.AlterField(
            model_name='sessionequipment',
            name='quantity_reserved',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sessionequipment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reservations', to='sessions_app.session'),
        ),
        migrations.AlterField(
            model_name='sessionsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_links', to='courses.section'),
        ),
        migrations.AlterField(
            model_name='sessionsection',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_links', to='sessions_app.session'),
        ),
        migrations.AddConstraint(
            model_name='sessionequipment',
            constraint=models.UniqueConstraint(fields=('session', 'equipment'), name='unique_equipment_per_session'),
        ),
        migrations.AddConstraint(
            model_name='sessionsection',
            constraint=models.UniqueConstraint(fields=('session', 'section'), name='unique_section_per_session'),
        ),
    ]
