# Generated by Django 5.2.6 on 2026-08-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('layout_type', models.CharField(choices=[('POSTER', 'Affiche'), ('SLIDE', 'Diapositive'), ('DOCUMENT', 'Document administratif')], default='SLIDE', max_length=20)),
                ('template_file', models.CharField(blank=True, help_text='Chemin ou identifiant du gabarit exploite par le Frontend.', max_length=500)),
            ],
            options={
                'verbose_name': 'gabarit',
                'verbose_name_plural': 'gabarits',
                'ordering': ['name'],
            },
        ),
    ]
