# Generated by Django 5.2.6 on 2026-08-28 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slidetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_matricule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
