# Generated by Django 5.2.17 on 2026-08-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('TITLE', 'Titre / En-tête'), ('TEXT', 'Paragraphe Texte'), ('IMAGE', 'Image avec légende'), ('CODE', 'Extrait de code'), ('LIST', 'Liste à puces'), ('CALLOUT', "Encart d'attention")], max_length=20),
        ),
    ]
