# Generated by Django 5.2.17 on 2026-08-29 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='courses.course'),
        ),
    ]
